{{- if .Values.secrets -}}
---

apiVersion: v1
data:
{{ toYaml .Values.secrets | indent 2}}
kind: Secret
metadata:
  name: {{ template "fusion.api-gateway.fullname" . }}
  labels:
    {{ include "fusion.api-gateway.labels" . | nindent 4 }}
type: Opaque

{{- end -}}
