{{- $tlsEnabled := include "fusion.tls.enabled" $ -}}
{{- range $i, $nodePool := .Values.nodePools }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "solr.fullname" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}"
  labels:
{{ include "solr.common.labels" $ | indent 4 }}
    app.kubernetes.io/component: "server"
    app.kubernetes.io/solrpool: "{{ $nodePool.name }}"
  annotations:
{{- toYaml ( $nodePool.annotations | default $.Values.annotations ) | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "solr.name" $ }}"
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      app.kubernetes.io/component: "server"
      app.kubernetes.io/solrpool: "{{ $nodePool.name }}"
  serviceName: "{{ include "solr.fullname" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}-headless"
  replicas: {{ $nodePool.replicaCount | default $.Values.replicaCount }}
  updateStrategy: {{ toYaml ($nodePool.updateStrategy | default $.Values.updateStrategy) | nindent 4}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "solr.name" $ }}"
        app.kubernetes.io/instance: "{{ $.Release.Name }}"
        app.kubernetes.io/component: "server"
        app.kubernetes.io/solrpool: "{{ $nodePool.name }}"
      annotations:
{{ toYaml ( $nodePool.podAnnotations | default $.Values.podAnnotations ) | indent 8 }}
    spec:
      serviceAccountName: "{{ $.Values.rbac.serviceAccountName | default (include "solr.fullname" $) }}"
    {{- if or $nodePool.nodeSelector $.Values.nodeSelector }}
      nodeSelector: {{ toYaml ($nodePool.nodeSelector | default $.Values.nodeSelector) | nindent 8 }}
    {{- end }}
      imagePullSecrets: {{ $.Values.image.imagePullSecrets | toYaml | nindent 12 }}
      {{- if ($nodePool.priorityClassName | default $.Values.priorityClassName) }}
      priorityClassName: "{{ ($nodePool.priorityClassName | default $.Values.priorityClassName) }}"
      {{- end }}
      {{- if ($nodePool.tolerations | default $.Values.tolerations) }}
      tolerations: {{ toYaml ($nodePool.tolerations | default $.Values.tolerations) | nindent 8 }}
      {{- end }}
      {{- if ($nodePool.schedulerName | default $.Values.schedulerName) }}
      schedulerName: {{ ($nodePool.schedulerName | default $.Values.schedulerName) | quote }}
      {{- end }}

      affinity:
{{ tpl (toYaml ($nodePool.affinity | default $.Values.affinity)) $  | indent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: shared
          emptyDir: {}
{{- if $tlsEnabled }}
{{ $params := dict "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.volumes" $params | indent 8 }}
{{- end }}
{{- if $.Values.additionalVolumes }}
        {{ toYaml $.Values.additionalVolumes | nindent 8 }}
{{- end }}
{{- if $.Values.config.solrxml}}
        - name: solr-xml
          configMap:
            name: {{ template "solr.configmap-name" $ }}
            items:
              - key: solr.xml
                path: solr.xml
{{- end }}
{{ include "gcs-secret-volume" $ | indent 8 }}
      initContainers:
{{- if $.Values.setAvailabilityZone }}
        - name: set-solr-zone
          image: {{ $.Values.initContainer.image.solrzoneImageName }}
          resources: {{ toYaml $.Values.initContainer.resources | nindent 12 }}
          command:
            - '/bin/bash'
            - '-c'
            - |
              #!/bin/bash -e

              echo "${NODE_NAME}"
              if kubectl get node "${NODE_NAME}"; then
                topology_zone=$(kubectl get node "${NODE_NAME}" -o jsonpath='{.metadata.labels.topology\.kubernetes\.io/zone}')
                if [[ "${topology_zone}" == "" ]]; then
                  topology_zone=$(kubectl get node "${NODE_NAME}" -o jsonpath='{.metadata.labels.failure-domain\.beta\.kubernetes\.io/zone}')
                fi
                if [[ "${topology_zone}" == "" ]]; then
                  echo "Zone could not be found from label, not setting"
                else
                  echo "export SOLR_OPTS=\"\${SOLR_OPTS} -Dsolr_zone=${topology_zone}\"" > /mnt/shared/zone.sh
                fi
              else
                echo "Unable to fetch node information"
              fi

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: shared
              mountPath: /mnt/shared
{{- end }}
{{- if $tlsEnabled }}
{{- $sep:= "" -}}
{{- if not (eq $nodePool.name "" ) -}}
{{- $sep = "-" -}}
{{- end }}
{{- $params := dict "Release" $.Release "global" $.Values.global "tls" $.Values.tls "tlsServiceName" ( printf "%s%s%s-headless" (include "solr.fullname" $) $sep ($nodePool.name) )  "keytoolUtils" $.Values.keytoolUtils  "additionalServices" (list ( include "solr.service-name" $ )) "securityContext" $.Values.securityContext }}
{{- include "fusion.tls.init-container-v2" $params | nindent 8 }}
{{- end }}
        - name: check-zk
          image: {{ $.Values.initContainer.image.repository }}/check-fusion-dependency:v1.2.0
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
          args:
            - zookeeper
          resources:
            requests:
              cpu: 200m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 32Mi
          env:
            - name: ZOOKEEPER_CONNECTION_STRING
              value: {{ include "fusion.zkConnectionString" $ }}
            - name: CHECK_INTERVAL
              value: {{ $.Values.zkInitCheckInterval | default "5s" }}
            - name: CHECK_TIMEOUT
              value: {{ $.Values.zkInitCheckTimeout | default "2s" }}
            - name: TIMEOUT
              value: {{ $.Values.zkInitTimeout | default "2m" }}
        {{- if $tlsEnabled }}
            - name: ADDITIONAL_CA_CERTIFICATE
              value: "/tls/ca.crt"
            - name: "TLS_ENABLED"
              value: "true"
          volumeMounts:
            - name: keystore-volume
              mountPath: /tls
        {{- end }}
{{- if $tlsEnabled }}
        - name: "enable-tls-in-solr"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          resources: {{ toYaml $.Values.initContainer.resources | nindent 12 }}
          command:
            - "sh"
            - "-c"
            - |
              /opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost "{{ template "fusion.zkSolrConnectionString" $ }}" -cmd clusterprop -name urlScheme -val https
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "-Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/tls/keystore.jks -Dzookeeper.ssl.trustStore.location=/tls/truststore.jks -Dzookeeper.ssl.keyStore.password={{ $.Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ $.Values.tls.keystorePassword }}"
          volumeMounts:
            - name: keystore-volume
              mountPath: /tls
{{ end }}

{{- if $.Values.additionalInitContainers }}
        {{ toYaml $.Values.additionalInitContainers | nindent 8 }}
{{- end }}
      containers:
        - name: solr
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources: {{ toYaml ($nodePool.resources| default $.Values.resources) | nindent 12 }}
          ports:
            - containerPort: {{ $.Values.port }}
              name: solr-client
          env:
{{- if  ($nodePool.solrGcTune| default $.Values.solrGcTune) }}
            - name: "GC_TUNE"
              value: "{{ ($nodePool.solrGcTune| default $.Values.solrGcTune) }}"
{{- end }}
            - name: "SOLR_OPTS"
              value: "{{ if not (or ($nodePool.disableNodeType) (eq $nodePool.name "")) }}-D{{ $.Values.nodePoolIdentifier}}={{ $nodePool.name }} {{ end }}{{ $nodePool.solrOpts | default $.Values.solrOpts }} {{- if $tlsEnabled }} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/ssl/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/ssl/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ $.Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ $.Values.tls.keystorePassword }} {{- end }}"
            - name: "OOM"
              value: "{{ $.Values.memoryBehavior }}"
            - name: "SOLR_JAVA_MEM"
              value: "{{ $nodePool.javaMem | default $.Values.javaMem }}"
            - name: "SOLR_HOME"
              value: "/var/solr/data"
            - name: "SOLR_PORT"
              value: "{{ $.Values.port }}"
            - name: "POD_HOSTNAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "SOLR_HOST"
              value: "$(POD_HOSTNAME).{{ include "solr.fullname" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}-headless{{ if not ( eq $.Values.serviceDnsName "" ) }}.{{ $.Release.Namespace }}.{{ $.Values.serviceDnsName }}{{ end }}"
            - name: "ZK_HOST"
              value: "{{ template "fusion.zkSolrConnectionString" $ }}"
            - name: "SOLR_LOG_LEVEL"
              value: "{{ $nodePool.logLevel | default $.Values.logLevel }}"
            - name: "SOLR_JAVA_STACK_SIZE"
              value: "{{ $.Values.solrJavaStackSize }}"
            - name: SOLR_REQUESTLOG_ENABLED
              value: "{{ $nodePool.solrRequestLogEnabled | default $.Values.solrRequestLogEnabled }}"
{{- if $.Values.solrModules }}
            - name: SOLR_MODULES
              value: {{ $.Values.solrModules }}
{{- end }}
{{- if $.Values.externalFileFieldRoot }}
            - name: EXTERNAL_ROOT_PATH
              value: {{ $.Values.externalFileFieldRoot }}
{{- end }}
{{ if $tlsEnabled }}
            - name: "SOLR_SSL_ENABLED"
              value: "true"
            - name: "SOLR_SSL_KEY_STORE"
              value: "/etc/ssl/keystores/keystore.jks"
            - name: "SOLR_SSL_KEY_STORE_PASSWORD"
              value: "{{ $.Values.tls.keystorePassword }}"
            - name: "SOLR_SSL_TRUST_STORE"
              value: "/etc/ssl/keystores/truststore.jks"
            - name: "SOLR_SSL_TRUST_STORE_PASSWORD"
              value: "{{ $.Values.tls.keystorePassword }}"
            - name: "SOLR_SSL_WANT_CLIENT_AUTH"
              value: "{{ $.Values.tls.wantClientAuth }}"
            - name: "SOLR_SSL_NEED_CLIENT_AUTH"
              value: "{{ $.Values.tls.needClientAuth }}"
            - name: "SOLR_SSL_CHECK_PEER_NAME"
              value: "{{ $.Values.tls.checkPeerName }}"
{{ end }}
          livenessProbe:
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
            httpGet:
            {{- if $tlsEnabled }}
              scheme: "HTTPS"
            {{- else }}
              scheme: "HTTP"
            {{- end }}
              path: /solr/admin/info/health
              port: {{ $.Values.port }}
          readinessProbe:
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            timeoutSeconds:  {{ $.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
            httpGet:
            {{- if $tlsEnabled }}
              scheme: "HTTPS"
            {{- else }}
              scheme: "HTTP"
            {{- end }}
              path: /solr/admin/info/health
              port: {{ $.Values.port }}
          volumeMounts:
            - name: {{ template "solr.pvc-name" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}
              mountPath: /var/solr
            - name: shared
              mountPath: /docker-entrypoint-initdb.d
{{- if $.Values.additionalVolumeMounts }}
        {{ toYaml $.Values.additionalVolumeMounts | nindent 12 }}
{{- end }}

{{- if $.Values.config.solrxml }}
            - name: solr-xml
              mountPath: /opt/solr/server/solr/solr.xml
              subPath: solr.xml
{{- end }}
{{ if $tlsEnabled }}
            - name: "keystore-volume"
              mountPath: "/etc/ssl/keystores"
{{ end }}
  {{ if $.Values.enableExternalFiles }}
        - name: process-raw
          image: "{{ $.Values.processRaw.image.repository }}/{{ $.Values.processRaw.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources: {{ toYaml ($nodePool.resources| default $.Values.processRaw.resources) | nindent 12 }}
          lifecycle:
            postStart:
              exec:
                command: ["mkdir", "-p", "/var/solr/rawTo"]
          args: ['process-raw']
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "{{ $.Values.processRaw.javaToolOptions }}
        {{- if $tlsEnabled }} -Dlogging.config=classpath:logback-kube-tls.xml {{- else }} -Dlogging.config=classpath:logback-kube.xml {{- end -}}
        {{- if $tlsEnabled }} -Djavax.net.ssl.trustStore=/etc/ssl/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword={{ $.Values.tls.keystorePassword }} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/ssl/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/ssl/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ $.Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ $.Values.tls.keystorePassword }}{{- end -}}
        "
  {{ if $.Values.enableExternalFiles }}
            - name: RAW_FROM
              value: "{{ $.Values.processRaw.cloudRoot }}/{{ $.Values.processRaw.rawFrom }}"
            - name: RAW_TO
              value: "file:///var/solr/rawTo"
            - name: PROCESSED_TO
              value: "file://{{ $.Values.externalFileFieldRoot }}"
{{ if and ($.Values.enableExternalFiles) (has "gcs" $.Values.enabledStorage) -}}
{{ include "gcs-secret-env" $ | indent 12 }}
{{ end }}
{{ if and ($.Values.enableExternalFiles) (has "s3" $.Values.enabledStorage) }}
{{ include "s3-secret-envs" $ | indent 12 }}
{{ end }}
{{- end }}
            - name: ZOOKEEPER_PATH
              value: {{ include "fusion.zkConnectionString" $ }}
            - name: INDEX_ROOT
              value: "file:///var/solr/data"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: "COMPONENT"
              value: "process-raw"
          volumeMounts:
            - name: {{ template "solr.pvc-name" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}
              mountPath: "/var/solr"
  {{ include "gcs-secret-volume-mount" $ | indent 12 }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "solr.pvc-name" $ }}{{- if not (eq $nodePool.name "") -}}-{{- end -}}{{ $nodePool.name }}
        annotations:
          pv.beta.kubernetes.io/gid: "8983"
      spec:
        accessModes:
{{ toYaml $.Values.volumeClaimTemplates.accessModes | indent 10 }}
{{- if not ( eq ( $nodePool.storageClassName | default $.Values.volumeClaimTemplates.storageClassName ) "" ) }}
        storageClassName: "{{ $nodePool.storageClassName | default $.Values.volumeClaimTemplates.storageClassName }}"
{{- end }}
        resources:
          requests:
            storage: {{ $nodePool.storageSize | default $.Values.volumeClaimTemplates.storageSize }}

{{- end -}}
