annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 3.1.0
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.28
description: Apache Kafka is a distributed streaming platform designed to build real-time
  pipelines and can be used as a message broker or as a replacement for a log aggregation
  solution for big data applications.
home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: kafka
sources:
- https://github.com/bitnami/bitnami-docker-kafka
- https://kafka.apache.org/
version: 16.2.32
