apiVersion: v1
appVersion: 9.1.1
description: A helm chart to install apache solr
home: http://lucene.apache.org/solr/
keywords:
- solr
maintainers:
- email: ian.thebridge@lucidworks.com
  name: Ian Thebridge
name: solr
sources:
- https://gitbox.apache.org/repos/asf?p=lucene-solr.git
version: 2.12.6
