{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
{{- $jsonOutput := ( eq (include "fusion.loggingJSONOutput" .) "true" ) }}
{{- $logstashHost := (include "fusion.logstashHost" .) -}}
{{- $logPulsar := ( eq (include "fusion.loggingDisablePulsar" .) "false" ) -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusion.webapps.fullname" . }}
  labels:
    {{ include "fusion.webapps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "webapps"
      app.kubernetes.io/part-of: "fusion"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "webapps"
        app.kubernetes.io/part-of: "fusion"
    spec:
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
        {{ tpl (toYaml .Values.affinity) . | nindent 8 }}
    {{- end }}
      volumes:
        - name: workdir
          emptyDir: {}
        - name: webappsdir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: secrets
          secret:
            secretName: service-account-key
            items:
              - key: sa
                path: service-account-key
{{- if $tlsEnabled }}
{{ $params := dict "tlsServiceName" "webapps" "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.volumes" $params | indent 8 }}
{{- end }}
      initContainers:
{{- if $tlsEnabled -}}
{{ $params := dict "tlsServiceName" "webapps" "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils "securityContext" $.Values.securityContext }}
{{ include "fusion.tls.init-container-v2" $params | indent 8 }}
{{- end }}
{{- include "fusion.initContainers.checkZk-v2" . | nindent 8 }}
{{- include "fusion.initContainers.checkPulsar-v2" . | nindent 8 }}
      containers:
      - name: webapps
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        args:
          - "--spring.profiles.active=kubernetes,jwt,fusion{{- if $tlsEnabled }},tls{{- end }}{{- if $jsonOutput }},logjson{{- end }}{{- if $logstashHost }},logstash{{- end }}{{- if $logPulsar }},logpulsar{{- end }}"
          - "--spring.cloud.kubernetes.config.name={{ include "fusion.webapps.fullname" . }}"
        env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.javaToolOptions }}
{{- if $tlsEnabled }} -Dlogging.config=classpath:logback-kube-tls.xml {{- else }} -Dlogging.config=classpath:logback-kube.xml {{- end }}
{{- if $tlsEnabled }} -Djavax.net.ssl.trustStore=/etc/ssl/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword={{ .Values.tls.keystorePassword }} -Djavax.net.ssl.trustStoreType=PKCS12 -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/ssl/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/ssl/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ .Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ .Values.tls.keystorePassword }}{{- end -}}
"
          {{ if $logstashHost }}
          - name: "LOGSTASH_HOST"
            value: "{{ $logstashHost }}"
          {{ end }}
          - name: "COMPONENT"
            value: "webapps"
          - name: "PULSAR_TENANT"
            value: "{{ include "fusion.webapps.kubeNamespace" . }}"
          - name: "PULSAR_SERVICE_URL"
            value: "{{ include "fusion.webapps.pulsarServiceUrl" . }}"
        ports:
          - containerPort: {{ .Values.port }}
            name: "jetty"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          httpGet:
            path: /actuator/health
            port: "jetty"
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "{{ .Values.preStopSleepTime }}"]
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
          - name: tmp
            mountPath: /tmp
          - name: workdir
            mountPath: "/app/var"
          - name: webappsdir
            mountPath: "/app/var/webapps"
{{- if $tlsEnabled }}
          - name: "keystore-volume"
            mountPath: "/etc/ssl/keystores"
{{- end }}
