apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logservices.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: getambassador.io
  scope: Namespaced
  names:
    plural: logservices
    singular: logservice
    kind: LogService
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: LogService is the Schema for the logservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LogServiceSpec defines the desired state of LogService
            properties:
              ambassador_id:
                description: "AmbassadorID declares which Ambassador instances should pay attention to this resource. If no value is provided, the default is: \n    ambassador_id:    - \"default\""
                items:
                  type: string
                type: array
              driver:
                enum:
                - tcp
                - http
                type: string
              driver_config:
                properties:
                  additional_log_headers:
                    items:
                      properties:
                        during_request:
                          type: boolean
                        during_response:
                          type: boolean
                        during_trailer:
                          type: boolean
                        header_name:
                          type: string
                      type: object
                    type: array
                type: object
              flush_interval_byte_size:
                type: integer
              flush_interval_time:
                type: integer
              grpc:
                type: boolean
              service:
                type: string
              stats_name:
                type: string
            type: object
        type: object
    served: true
    storage: true
