apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.24
description: A helm chart to install the templating component
keywords:
- fusion
- templating
maintainers:
- email: ian.thebridge@lucidworks.com
  name: Ian Thebridge
- email: tim.potter@lucidworks.com
  name: Timothy Potter
name: templating
version: 0.4.20
