affinity: {}
annotations: {}
autoscaling:
  enabled: false
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 1
component: connector-plugin
deploymentStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
fusion-common-utils:
  global: {}
hazelcast:
  yaml:
    hazelcast:
      map:
        shared_cache_*:
          eviction:
            eviction-policy: LRU
            max-size-policy: USED_HEAP_PERCENTAGE
            size: 10
          max-idle-seconds: 3600
      network:
        join:
          kubernetes:
            enabled: true
            service-name: connector-plugin
            service-port: 5701
          multicast:
            enabled: false
hazelcastPort: "5701"
image:
  imagePullSecrets: []
  name: connector-plugin
  pullPolicy: IfNotPresent
  repository: lucidworks
  tag: latest
javaToolOptions: -XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=40.0 -Xss1024k -Dhttp.maxConnections=1000
  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps -XX:+StartAttachListener
  -Djdk.attach.allowAttachSelf=true
kafka:
  servicePort: "9092"
  serviceTLSPort: "9092"
kafkaReplicaCount: 1
keytoolUtils:
  image:
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    name: keytool-utils
    repository: lucidworks
    tag: v2.1.2
livenessProbe:
  failureThreshold: 20
  initialDelaySeconds: 65
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
name: connector-plugin
networkPolicy:
  additionalEgressRules: []
  additionalIngressRules: []
  dnsAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
  enabled: false
  kubernetesAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
nodeSelector: {}
pluginValues: []
pod:
  annotations: {}
podDisruptionBudget:
  maxUnavailable: 1
port:
  external: 9020
  internal: 9020
preStopSleepTime: 15
rbac:
  create: true
readinessProbe:
  failureThreshold: 20
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
replicaCount: 0
securityContext:
  fsGroup: 8764
  runAsNonRoot: true
  runAsUser: 8764
serviceName: connector-plugin
springProfiles: k8s,jwt
storage:
  connectorDataPvcEnabled: false
tls:
  caSecret:
    name: ""
  certSecret:
    name: ""
  clusterDomain: svc.cluster.local
  duration: 8760h
  enabled: false
  generateCert: true
  generateJKS: true
  issuerRef:
    kind: Issuer
    name: fusion-ca-issuer
  keystorePassword: changeit
  renewBefore: 8464h
trustedCertificates:
  enabled: false
zkPort: 2181
zkReplicaCount: 3
zkTLSPort: 2281
