{{- if .Values.rbac.create -}}

{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "configmaps", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps", "extensions" ]
    resources: [ "deployments", "replicasets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "fusion.lucidworks.com" ]
    resources: [ "connector-plugins" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
{{- if $tlsEnabled }}
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
{{- end }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "fusion.connectors-backend.fullname" . }}"
    apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.plugins.crd.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [ "get", "create", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "fusion.connectors-backend.fullname" . }}"
    namespace: {{ .Release.Namespace }}
---
{{- end }}

{{- end }}
