---

apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: "PodDisruptionBudget"
metadata:
  name: "{{ template "fusion.fusion-indexing.fullname" . }}"
  labels:
    {{ include "fusion.fusion-indexing.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "fusion-indexing"
      app.kubernetes.io/part-of: "fusion"
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
