apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.28
description: A helm chart to install the shared resources for fusion
keywords:
- fusion
- fusion-resources
maintainers:
- email: ian.thebridge@lucidworks.com
  name: Ian Thebridge
name: fusion-resources
version: 1.5.6
