{{- $networkPoliciesEnabled := false -}}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicyEnabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- else if .Values.prune.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}
{{- else if .Values.prune.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}

{{ if $networkPoliciesEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "fusion.solr-backup-runner.fullname" .  }}-prune"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "fusion.solr-backup-runner.fullname" . }}-prune"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "solr-backup-runner"
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{- if .Values.prune.networkPolicy.additionalIngressRules }}
{{ toYaml .Values.prune.networkPolicy.additionalIngressRules | nindent 4 }}
{{ else }} []
{{- end }}
  egress:
{{- if .Values.prune.networkPolicy.additionalEgressRules }}
{{ toYaml .Values.prune.networkPolicy.additionalEgressRules | nindent 4 }}
{{ else }} []
{{- end }}
{{- end }}
