{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fusion.fusion-admin.fullname" .  }}
  labels:
    {{ include "fusion.fusion-admin.labels" . | nindent 4 }}
spec:
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "fusion-admin-tls-secret"
{{ end }}
  rules:
  - host: admin-{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.pathtype }}
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ include "fusion.fusion-admin.serviceName" .  }}}
            port:
              number: {{ .Values.service.externalPort }}
{{- end -}}
