---

apiVersion: v1
kind: Secret
metadata:
  name: service-account-key
data:
  sa: "{{ .Values.serviceAccountKey | default (derivePassword 1 "long" .Release.Namespace .Release.Name .Chart.Name) | b64enc }}"
type: Opaque
