---

{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fusion.templating.serviceName" . }}"
  labels:
    app.kubernetes.io/target-image-tag: "{{ .Values.image.tag }}"
{{- if $tlsEnabled }}
    secured: "true"
{{- end }}
    {{- include "fusion.templating.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: "templating"
    app.kubernetes.io/part-of: "fusion"
  type: {{ .Values.service.type }}
