apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.24
description: Helm Chart to deploy fusion-admin service in Kubernetes
maintainers:
- email: ian.thebridge@lucidworks.com
  name: Ian Thebridge
name: fusion-admin
version: 1.10.2
