image:
  debug: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  repository: lucidworks
  tag: latest
nodeSelector:
  default: {}
  deploy:
    seldon: null
resources:
  default: {}
  deploy:
    seldon: null
securityContext:
  capabilities:
    drop:
    - NET_RAW
tls:
  enabled: false
  keystorePassword: changeit
tolerations:
  default: []
  deploy:
    seldon: null
