{{- if .Values.rbac.create -}}

{{- $tlsEnabled := include "fusion.tls.enabled" $ -}}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "configmaps", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps", "extensions" ]
    resources: [ "deployments", "replicasets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "fusion.lucidworks.com" ]
    resources: [ "connector-plugins" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
{{- if $tlsEnabled }}
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
{{- end }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fusion.connectors-backend.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "fusion.connectors-backend.fullname" . }}"
    apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "fusion.connectors-backend.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.plugins.crd.create }}
---
{{- end }}

{{- end }}
