apiVersion: v2
appVersion: 5.9.0
dependencies:
- alias: admin-ui
  condition: fusion.admin-ui.enabled,admin-ui.enabled
  name: admin-ui
  repository: https://charts.lucidworks.com
  version: 1.3.14
- alias: api-gateway
  condition: fusion.api-gateway.enabled,api-gateway.enabled
  name: api-gateway
  repository: https://charts.lucidworks.com
  version: 1.12.15
- alias: apps-manager
  condition: fusion.apps-manager.enabled,apps-manager.enabled
  name: apps-manager
  repository: https://charts.lucidworks.com
  version: 0.1.5
- alias: argo-common-workflows
  condition: fusion.argo-common-workflows.enabled,argo-common-workflows.enabled
  name: argo-common-workflows
  repository: https://charts.lucidworks.com
  version: 1.0.12
- alias: argo
  condition: fusion.argo.enabled,argo.enabled
  name: argo
  repository: https://charts.lucidworks.com
  version: 1.0.9
- alias: async-parsing
  condition: fusion.async-parsing.enabled,async-parsing.enabled
  name: async-parsing
  repository: https://charts.lucidworks.com
  version: 0.1.9
- alias: auth-ui
  condition: fusion.auth-ui.enabled,auth-ui.enabled
  name: auth-ui
  repository: https://charts.lucidworks.com
  version: 1.3.13
- alias: classic-rest-service
  condition: fusion.classic-rest-service.enabled,classic-rest-service.enabled
  name: classic-rest-service
  repository: https://charts.lucidworks.com
  version: 2.3.1
- alias: classification
  condition: fusion.classification.enabled,classification.enabled
  name: classification
  repository: https://charts.lucidworks.com
  version: 1.0.6
- alias: cloud-signals
  condition: fusion.cloud-signals.enabled,cloud-signals.enabled
  name: cloud-signals
  repository: https://charts.lucidworks.com
  version: 0.3.10
- alias: connector-plugin
  condition: fusion.connector-plugin.enabled,connector-plugin.enabled
  name: connector-plugin
  repository: https://charts.lucidworks.com
  version: 1.5.1
- alias: connectors-backend
  condition: fusion.connectors-backend.enabled,connectors-backend.enabled
  name: connectors-backend
  repository: https://charts.lucidworks.com
  version: 2.2.1
- alias: connectors
  condition: fusion.connectors.enabled,connectors.enabled
  name: connectors
  repository: https://charts.lucidworks.com
  version: 2.2.1
- alias: fusion-admin
  condition: fusion.fusion-admin.enabled,fusion-admin.enabled
  name: fusion-admin
  repository: https://charts.lucidworks.com
  version: 1.10.2
- alias: fusion-data-augmentation
  condition: fusion.fusion-data-augmentation.enabled,fusion-data-augmentation.enabled
  name: fusion-data-augmentation
  repository: https://charts.lucidworks.com
  version: 1.0.9
- alias: fusion-indexing
  condition: fusion.fusion-indexing.enabled,fusion-indexing.enabled
  name: fusion-indexing
  repository: https://charts.lucidworks.com
  version: 2.9.13
- alias: fusion-resources
  condition: fusion.fusion-resources.enabled,fusion-resources.enabled
  name: fusion-resources
  repository: https://charts.lucidworks.com
  version: 1.5.0
- alias: insights
  condition: fusion.insights.enabled,insights.enabled
  name: insights
  repository: https://charts.lucidworks.com
  version: 1.2.6
- alias: job-launcher
  condition: fusion.job-launcher.enabled,job-launcher.enabled
  name: job-launcher
  repository: https://charts.lucidworks.com
  version: 1.7.34
- alias: job-rest-server
  condition: fusion.job-rest-server.enabled,job-rest-server.enabled
  name: job-rest-server
  repository: https://charts.lucidworks.com
  version: 1.9.23
- alias: kafka
  condition: fusion.kafka.enabled,kafka.enabled
  name: kafka
  repository: https://charts.lucidworks.com
  version: 16.2.30
- alias: ml-model-service
  condition: fusion.ml-model-service.enabled,ml-model-service.enabled
  name: ml-model-service
  repository: https://charts.lucidworks.com
  version: 1.20.26
- alias: pm-ui
  condition: fusion.pm-ui.enabled,pm-ui.enabled
  name: pm-ui
  repository: https://charts.lucidworks.com
  version: 1.4.12
- alias: query-pipeline
  condition: fusion.query-pipeline.enabled,query-pipeline.enabled
  name: query-pipeline
  repository: https://charts.lucidworks.com
  version: 1.11.2
- alias: question-answering
  condition: fusion.question-answering.enabled,question-answering.enabled
  name: question-answering
  repository: https://charts.lucidworks.com
  version: 1.4.8
- alias: recommender
  condition: fusion.recommender.enabled,recommender.enabled
  name: recommender
  repository: https://charts.lucidworks.com
  version: 0.12.8
- alias: reverse-search
  condition: fusion.reverse-search.enabled,reverse-search.enabled
  name: reverse-search
  repository: https://charts.lucidworks.com
  version: 0.0.15
- alias: rules-ui
  condition: fusion.rules-ui.enabled,rules-ui.enabled
  name: rules-ui
  repository: https://charts.lucidworks.com
  version: 1.4.14
- alias: seldon-core-operator
  condition: fusion.seldon-core-operator.enabled,seldon-core-operator.enabled
  name: seldon-core-operator
  repository: https://charts.lucidworks.com
  version: 1.16.5
- alias: solr-backup-runner
  condition: fusion.solr-backup-runner.enabled,solr-backup-runner.enabled
  name: solr-backup-runner
  repository: https://charts.lucidworks.com
  version: 1.0.6
- alias: solr
  condition: fusion.solr.enabled,solr.enabled
  name: solr
  repository: https://charts.lucidworks.com
  version: 2.12.2
- alias: templating
  condition: fusion.templating.enabled,templating.enabled
  name: templating
  repository: https://charts.lucidworks.com
  version: 0.4.20
- alias: webapps
  condition: fusion.webapps.enabled,webapps.enabled
  name: webapps
  repository: https://charts.lucidworks.com
  version: 1.7.23
- alias: zookeeper
  condition: fusion.zookeeper.enabled,zookeeper.enabled
  name: zookeeper
  repository: https://charts.lucidworks.com
  version: 2.6.2
description: A helm chart to install Lucidworks Fusion
keywords:
- fusion
maintainers:
- email: ian.thebridge@lucidworks.com
  name: Ian Thebridge
name: fusion
version: 5.9.0
