---
{{- $tlsEnabled := include "fusion.tls.enabled" $ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fusion.query-pipeline.fullname" . }}"
  labels:
    {{ include "fusion.query-pipeline.labels" . | nindent 4 }}
data:
  application.yaml: |
    logging:
      level:
        root: {{ .Values.logLevelRoot }}
        org:
            springframework:
                cloud:
                    client:
                        discovery: TRACE
    management:
      health:
        solr:
          enabled: false
      endpoints:
        web:
          exposure:
            include: health, ready, prometheus
    jetty:
      server:
        stop:
          timeout: {{ .Values.serverStopTimeout }}
    ribbon:
      zookeeper:
        enabled: false
    spring:
      cloud:
        kubernetes:
          enabled: true
          ribbon:
            enabled: true
        zookeeper:
          connect-string: "{{ include "fusion.zkConnectionString" . }}"
          discovery:
            enabled: false
      sleuth:
        enabled: true
        log:
          slf4j:
            enabled: false
        zipkin:
          enabled: "{{ .Values.zipkinEnabled }}"
          baseUrl: "{{ .Values.zipkinUrl }}"
{{- if $tlsEnabled }}
    server:
      ssl:
        key-store-type: pkcs12
        key-store: /etc/ssl/keystores/keystore.jks
        key-store-password: {{ .Values.tls.keystorePassword }}
        trust-store: /etc/ssl/keystores/truststore.jks
        trust-store-password: {{ .Values.tls.keystorePassword }}

    kafka:
      properties:
        security.protocol: SSL
        ssl.truststore.location: /etc/ssl/keystores/truststore.jks
        ssl.truststore.password: {{ .Values.tls.truststorePassword | default .Values.tls.keystorePassword | quote }}
{{- end }}

    accesslog:
      enabled: {{ .Values.accessLogEnabled }}
    datadog:
      host: "{{ template "fusion.query-pipeline.datadogHost" . }}"
      port: {{ .Values.datadog.port }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fusion.query-pipeline.fullname" . }}-warming-queries"
  labels:
    {{ include "fusion.query-pipeline.labels" . | nindent 4 }}
data:
  warming_queries.json: |
    {{ .Values.warmingQueryJson | toJson }}
