---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fusion.job-rest-server.fullname" . }}"
  labels:
    {{ include "fusion.job-rest-server.labels" . | nindent 4 }}
data:
  application.yaml: |
    jetty:
      server:
        stop:
          timeout: {{ .Values.serverStopTimeout }}
    management:
      health:
        solr:
          enabled: false
    logging:
      level:
        root: {{ .Values.logLevelRoot }}
    ribbon:
      zookeeper:
        enabled: false
{{- if $tlsEnabled  }}
    server:
      ssl:
        key-store-type: pkcs12
        key-store: /etc/ssl/keystores/keystore.jks
        key-store-password: {{ .Values.tls.keystorePassword }}
        trust-store: /etc/ssl/keystores/truststore.jks
        trust-store-password: {{ .Values.tls.keystorePassword }}
{{- end }}
    spring:
{{- if .Values.config.springSecurity }}
      security:
{{ tpl .Values.config.springSecurity . | indent 8 }}
{{- end }}
      cloud:
        kubernetes:
          enabled: true
          ribbon:
            enabled: true
          secrets:
            enabled: true
          config:
            enabled: true
        zookeeper:
          connect-string: "{{ include "fusion.zkConnectionString" . }}"
          discovery:
            enabled: false
      sleuth:
        enabled: false
      zipkin:
        enabled: false # enable if running zipkin server
        # baseUrl: http://localhost:9411/
    accesslog:
      enabled: {{ .Values.accessLogEnabled }}
