{{- if .Values.secrets -}}
---

apiVersion: v1
data:
{{ toYaml .Values.secrets | indent 2}}
kind: Secret
metadata:
  name: {{ template "fusion.jobLauncher.fullname" . }}
  labels:
    app: "{{ template "fusion.jobLauncher.name" . }}"
{{ include "fusion.jobLauncher.labels" . | indent 4 }}
type: Opaque

{{- end -}}
