{{- if .Values.trustedCertificates.enabled -}}
---
apiVersion: v1
data:
{{- range $key, $val := .Values.trustedCertificates.files }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: custom-trusted-certs-secret-classic
type: Opaque

{{- end -}}
