---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusion.insights.serviceName" . }}
  labels:
    app.kubernetes.io/target-image-tag: {{ .Values.image.tag }}
{{ include "fusion.insights.labels" . | indent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: "insights"
    app.kubernetes.io/part-of: "fusion"
  type: {{ .Values.service.type }}
