apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.24
description: A helm chart to install the admin-ui component
keywords:
- fusion
- admin-ui
- admin
maintainers:
- email: dmitriy.lyner@lucidworks.com
  name: Dmitriy Lyner
- email: graham.holt@lucidworks.com
  name: Graham Holt
name: admin-ui
version: 1.3.14
