{{- $networkPoliciesEnabled := false -}}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicyEnabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}

{{ if $networkPoliciesEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion.apps-manager.fullname" .  }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "{{ .Values.component }}"
      app.kubernetes.io/part-of: "fusion"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "api-gateway"
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "fusion-query"
      ports:
        - protocol: TCP
          port: 9025
{{ if .Values.networkPolicy.additionalIngressRules }}
{{ toYaml .Values.networkPolicy.additionalIngressRules | nindent 4 }}
{{ end }}
  egress:
    # Define egress for DNS lookups
    - to: {{ .Values.networkPolicy.dnsAccess | toYaml | nindent 8 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # This outbound rule is required to talk to the kubernetes API services
    - to: {{ .Values.networkPolicy.kubernetesAccess | toYaml | nindent 8 }}
      ports:
        - protocol: TCP
          port: 443
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "query-pipeline"
      ports:
        - protocol: TCP
          port: 8787
    - to:
        - podSelector:
            matchLabels:
              app: "zookeeper"
      ports:
        - protocol: TCP
          port: 2181
        - protocol: TCP
          port: 2281
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "api-gateway"
      ports:
        - protocol: TCP
          port: 6764
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "solr"
      ports:
        - port: 8983
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "reverse-search"
      ports:
        - port: 8983
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "fusion-admin"
      ports:
        - protocol: TCP
          port: 8765
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "kafka"
      ports:
        - protocol: TCP
          port: 9092
{{ if .Values.networkPolicy.additionalEgressRules }}
{{ toYaml .Values.networkPolicy.additionalEgressRules | nindent 4 }}
{{ end }}
{{- end }}
