{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusion.classic-rest-service.fullname" . }}
  labels:
{{ include "fusion.classic-rest-service.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
data:
  application-k8s.yml: |-
    logging:
      file: {{ .Values.logdir }}/connectors-classic.log
    spring:
      profiles:
        include: default
      cloud:
        kubernetes:
          enabled: true
          ribbon:
            enabled: true
          secrets:
            enabled: true
        zookeeper:
          discovery:
            enabled: false
            instanceHost: {{ .Values.hostname }}
    ribbon:
      zookeeper:
        enabled: false
    services:
      zookeeper:
         connect-string: {{ include "fusion.zkConnectionString" . }}
    accesslog:
      enabled: {{ .Values.accessLogEnabled }}
    tika:
      address: "async-parsing:9005"
{{- if  $tlsEnabled  }}
    server:
      ssl:
        key-store-type: pkcs12
        key-store: /etc/ssl/keystores/keystore.jks
        key-store-password: {{ .Values.tls.keystorePassword }}
        trust-store: /etc/ssl/keystores/truststore.jks
        trust-store-password: {{ .Values.tls.keystorePassword }}
{{- end }}
    plugins:
      bootstrap:
        install: {{ .Values.bootstrapEnabled }}
