apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.24
description: A Helm chart to install the Spring-based fusion-indexing service
keywords:
- fusion
- indexing
- index
maintainers:
- email: support@lucidworks.com
  name: Lucidworks
name: fusion-indexing
version: 2.9.13
