{{- if .Values.secrets -}}
---

apiVersion: v1
data:
  {{ toYaml .Values.secrets | nindent 2}}
kind: Secret
metadata:
  name: {{ template "fusion.templating.fullname" . }}
  labels:
    {{ include "fusion.templating.labels" . | nindent 4 }}
type: Opaque

{{- end -}}
