apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.6.24
description: A helm chart to install the pm-ui component
keywords:
- fusion
- pm-ui
- pm
maintainers:
- email: dmitriy.lyner@lucidworks.com
  name: Dmitriy Lyner
- email: yuwen.fang@lucidworks.com
  name: Yuwen Fang
name: pm-ui
version: 1.4.12
