---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: "PodDisruptionBudget"
metadata:
  name: "{{ template "solr.fullname" . }}"
  labels:
{{ include "solr.common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "solr.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "server"
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
