{{- if .Values.config.solrxml -}}
---

apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ template "solr.configmap-name" . }}"
  labels:
{{ include "solr.common.labels" . | indent 4}}
data:
  solr.xml: |
{{ .Values.config.solrxml | indent 4 }}
{{- end -}}
