affinity: {}
annotations: {}
autoscaling:
  enabled: false
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 1
component: connectors-backend
deploymentStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
fusion-common-utils:
  global: {}
image:
  imagePullSecrets: []
  name: connectors-backend
  pullPolicy: IfNotPresent
  repository: lucidworks
  tag: latest
ingress:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      client_body_timeout 31536000s;
      grpc_read_timeout 31536000s;
      grpc_send_timeout 31536000s;
  enabled: false
  path: /
  pathtype: Prefix
  tls:
    enabled: false
javaToolOptions: -XX:+ExitOnOutOfMemoryError -XX:InitialRAMPercentage=40.0 -XX:MaxRAMPercentage=75.0
  -Xss256k -Dhttp.maxConnections=1000 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps
  -XX:+StartAttachListener -Djdk.attach.allowAttachSelf=true
kafka:
  servicePort: "9092"
  serviceTLSPort: "9092"
kafkaReplicaCount: 1
keytoolUtils:
  image:
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    name: keytool-utils
    repository: lucidworks
    tag: v2.1.2
livenessProbe:
  failureThreshold: 20
  initialDelaySeconds: 65
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
name: connectors-backend
networkPolicy:
  additionalEgressRules: []
  additionalIngressRules: []
  dnsAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
  enabled: false
  kubernetesAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
nodeSelector: {}
plugins:
  crd:
    create: true
  replicas: 1
  repository:
    id: fusion-download-hosting
    name: lucidworks-connector-plugins
pod:
  annotations: {}
podDisruptionBudget:
  maxUnavailable: 1
port:
  mainService:
    external: 8771
    internal: 8771
  pluginService:
    external: 8772
    internal: 8772
preStopSleepTime: 15
rbac:
  create: true
readinessProbe:
  failureThreshold: 20
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
replicaCount: 1
securityContext:
  runAsNonRoot: true
serviceName: connectors-backend
springProfiles: k8s,jwt
storage:
  connectorDataPvcEnabled: false
  size: 10Gi
  storageClass: ""
tls:
  caSecret:
    name: ""
  certSecret:
    name: ""
  clusterDomain: svc.cluster.local
  duration: 8760h
  enabled: false
  generateCert: true
  generateJKS: true
  issuerRef:
    kind: Issuer
    name: fusion-ca-issuer
  keystorePassword: changeit
  renewBefore: 8464h
zkPort: 2181
zkReplicaCount: 3
zkTLSPort: 2281
