---

apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: "PodDisruptionBudget"
metadata:
  name: {{ include "fusion.pm-ui.fullname" .  }}
  labels:
{{ include "fusion.pm-ui.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "pm-ui"
      app.kubernetes.io/part-of: "fusion"
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
