{{- $networkPoliciesEnabled := false -}}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicyEnabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}

{{ if $networkPoliciesEnabled }}
{{ $components:= list "api-gateway" "fusion-admin" "query-pipeline" "fusion-indexing" "fusion-features" "job-launcher" "job-rest-server" "ml-model-service" "sql-service" "classic-rest-service" "connectors-backend" "connectors" "webapps" "templating" "connector-plugin" "config-sync" "kafka" "apps-manager" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion.fusion-admin.fullname" .  }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component:  "fusion-admin"
      app.kubernetes.io/part-of: "fusion"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
{{- range $component := $components }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "{{ $component }}"
{{- end }}
      - podSelector:
          matchLabels:
            spark-role: driver
      - podSelector:
          matchLabels:
            spark-role: executor
      ports:
      - protocol: TCP
        port: 8765
{{ if .Values.networkPolicy.additionalIngressRules }}
{{ toYaml .Values.networkPolicy.additionalIngressRules | nindent 4 }}
{{ end }}
  egress:
# Define egress for DNS lookups
    - to: {{ .Values.networkPolicy.dnsAccess | toYaml | nindent 8 }}
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
# This outbound rule is required to talk to the kubernetes API services
    - to: {{ .Values.networkPolicy.kubernetesAccess | toYaml | nindent 8 }}
      ports:
      - protocol: TCP
        port: 443
    - to:
      - podSelector:
          matchLabels:
            app: "zookeeper"
      ports:
      - protocol: TCP
        port: 2181
      - protocol: TCP
        port: 2281
    - to:
      - podSelector:
          matchLabels:
            app: "logstash"
      ports:
      - protocol: TCP
        port: 9600
      - protocol: TCP
        port: 4560
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: "solr"
      ports:
      - protocol: TCP
        port: 8983
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "query-pipeline"
      ports:
      - protocol: TCP
        port: 8787
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "templating"
      ports:
        - protocol: TCP
          port: 5250
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "classic-rest-service"
      ports:
      - protocol: TCP
        port: 9000
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "connectors-backend"
      ports:
      - protocol: TCP
        port: 8771
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "connectors"
      ports:
      - protocol: TCP
        port: 9010
    - to:
      - podSelector:
          matchLabels:
              app.kubernetes.io/component: "connector-plugin"
      ports:
      - protocol: TCP
        port: 9020
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "fusion-admin"
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "fusion-indexing"
      ports:
      - protocol: TCP
        port: 8765
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "fusion-features"
      ports:
        - protocol: TCP
          port: 8769
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "job-rest-server"
      ports:
      - protocol: TCP
        port: 8081
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "ml-model-service"
      ports:
      - protocol: TCP
        port: 8086
      - protocol: TCP
        port: 6565
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "sql-service"
      ports:
      - protocol: TCP
        port: 8085
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "webapps"
      ports:
      - protocol: TCP
        port: 8780
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "api-gateway"
      ports:
      - protocol: TCP
        port: 6764
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "job-launcher"
      ports:
      - protocol: TCP
        port: 8083
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "kafka"
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - podSelector:
            matchLabels:
              app: "solr-autoscaling-operator"
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: "reverse-search"
      ports:
        - protocol: TCP
          port: 8983
{{- if .Values.networkPolicy.additionalEgressRules }}
{{ toYaml .Values.networkPolicy.additionalEgressRules | nindent 4 }}
{{ end }}
{{- end }}
