{{- if .Values.secrets -}}
---

apiVersion: v1
data:
  {{ toYaml .Values.secrets | nindent 2}}
kind: Secret
metadata:
  name: {{ template "fusion.query-pipeline.fullname" . }}
  labels:
    {{ include "fusion.query-pipeline.labels" . | nindent 4 }}
type: Opaque

{{- end -}}
