{{- if .Values.rbac.create }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "reverse-search.fullname" . }}"

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
rules:
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ include "reverse-search.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io


{{- if .Values.setAvailabilityZone }}
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
rules:
- apiGroups: [""]
  resources: [ "nodes" ]
  verbs: [ "get" ]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ include "reverse-search.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Namespace }}-{{ include "reverse-search.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- end }}
{{- end }}
